teams:
  RED: true
  BLUE: true
  GREEN: true
  YELLOW: true
  WHITE: true
  BLACK: true
  AQUA: true
  DARK_AQUA: true
  DARK_BLUE: true
  DARK_GRAY: true
  DARK_GREEN: true
  DARK_PURPLE: true
  DARK_RED: true
  GOLD: true
  GRAY: true
  LIGHT_PURPLE: true

max-game-duration: "1h" # Maximum duration of the game

bingo-card:
  name: "&aBingo Card &7(Right Click)"
  material: FILLED_MAP
  slot: 9
  locked: true # If true, the item will be locked in the inventory

bingo-team-selector:
  name: "&aTeam Selector &7(Right Click)"
  material: NETHER_STAR
  slot: 1
  locked: true # If true, the item will be locked in the inventory


goals:
  COLLECT_DIAMOND: # ID of the Goal
    name: "&fCollect a &bDiamond" # Display Name of the Goal (in the GUI)
    material: DIAMOND_ORE # Material of the Goal (in the GUI)

    goal-type: "COLLECT"
    goal-material: DIAMOND
    goal-amount: 1

  COLLECT_COAL:
    name: "&fCollect 32 &8Coal"
    material: COAL_ORE

    goal-type: "COLLECT"
    goal-material: COAL
    goal-amount: 32

  KILL_PIG:
    name: "&fKill a &dPig"
    material: PORKCHOP

    goal-type: "KILL"
    goal-entity: PIG
    goal-amount: 1

  GET_SPEED:
    name: "&fGet the &bSpeed &fPotion Effect"
    material: SUGAR

    goal-type: "POTION_EFFECT"
    goal-potion-effect: speed

  FIND_DESERT:
    name: "&fFind a &6Desert"
    material: SAND

    goal-type: "FIND_BIOME"
    goal-biome: DESERT

  DO_THE_DIE:
    name: "&fDie &c5 &ftimes"
    material: BARRIER

    goal-type: "DIE"
    goal-cause:
    goal-amount: 5